development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jira:
    site: 'https://scorefield1998.atlassian.net/'
    username: 'scorefield1998@gmail.com'
    api_token: 'ATATT3xFfGF0CFVr4MvF3XuwTtmtpquVD0TnYs3Zm5iVsWfzxdu-Lm1SsuArzqKk5qikKEIUMgmZqaek1RhROkQmYfWxfY5iVZiFo7-ycTY1YyEZ_HTHBUBIfaL77YKA8kMwc_-eA6N2667zMOZld1daB_xBi7qDE1iJ6FqA4kYVgQR747Go2Gw=0DEADD9D'
    project_key: 'KAN'

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jira:
    site: 'https://scorefield1998.atlassian.net/'
    username: 'scorefield1998'
    api_token: 'ATATT3xFfGF0CFVr4MvF3XuwTtmtpquVD0TnYs3Zm5iVsWfzxdu-Lm1SsuArzqKk5qikKEIUMgmZqaek1RhROkQmYfWxfY5iVZiFo7-ycTY1YyEZ_HTHBUBIfaL77YKA8kMwc_-eA6N2667zMOZld1daB_xBi7qDE1iJ6FqA4kYVgQR747Go2Gw=0DEADD9D'
    project_key: 'KAN'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jira:
    site: 'https://scorefield1998.atlassian.net/'
    username: 'scorefield1998'
    api_token: 'ATATT3xFfGF0CFVr4MvF3XuwTtmtpquVD0TnYs3Zm5iVsWfzxdu-Lm1SsuArzqKk5qikKEIUMgmZqaek1RhROkQmYfWxfY5iVZiFo7-ycTY1YyEZ_HTHBUBIfaL77YKA8kMwc_-eA6N2667zMOZld1daB_xBi7qDE1iJ6FqA4kYVgQR747Go2Gw=0DEADD9D'
    project_key: 'KAN'
